version: '2.1'

volumes:
    grafana_data: {}

services:
  grafana:
    image: grafana/grafana:master
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
    restart: unless-stopped
    expose:
      - 3000

  clickhouse-seed:
    image: yandex/clickhouse-server
    container_name: clickhouse-seed
    ports:
      - 8123:8123

  clickhouse-client:
    container_name: clickhouse-client
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

  cloki:
    image: qxip/cloki:latest
    container_name: loki
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-seed
      - DEBUG=true
    depends_on:
      - clickhouse-seed

  pastash:
    image: qxip/pastash-loki
    container_name: pastash
    volumes:
      - ./loki/pastash.json:/config/loki.conf
      - /var/log:/var/log:ro
