# This workflow will validate qryn using bun + clickhouse

name: QRYN BUN CI

on:
  push:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  workflow_dispatch:
    inputs:
      clickhouse_tag:
        description: 'Tag for ClickHouse (23.8-alpine)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [latest]
    services:
      clickhouse:
        image: "clickhouse/clickhouse-server:${{ github.event.inputs.clickhouse_tag || '23.8-alpine' }}"
        ports:
          - 8123:8123
          - 9000:9000
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}
    - run: rm -rf package-lock.json
    - run: git submodule init
    - run: git submodule update
    - run: bun install
    - name: Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1.8.7
      if: github.event_name != 'pull_request'
    - env:
        CLICKHOUSE_DB: qryn
        CLICKHOUSE_TSDB: qryn
        INTEGRATION_E2E: 1
        CLOKI_EXT_URL: 127.0.0.1:3100
        QRYN_LOGIN: a
        QRYN_PASSWORD: b
      run: bun --bun qryn.mjs >/dev/stdout & bun run test --forceExit
