# This workflow will validate qryn using nodejs + clickhouse

name: QRYN CI

on:
  push:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  workflow_dispatch:
    inputs:
      clickhouse_tag:
        description: 'Tag for ClickHouse (23.8-alpine)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 16.x, 20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      clickhouse:
        image: "clickhouse/clickhouse-server:${{ github.event.inputs.clickhouse_tag || '23.8-alpine' }}"
        ports:
          - 8123:8123
          - 9000:9000
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run postinstall
    - run: git submodule init
    - run: git submodule update
    - name: Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1.8.7      
    - env:
        CLICKHOUSE_DB: qryn
        CLICKHOUSE_TSDB: qryn
        INTEGRATION_E2E: 1
        CLOKI_EXT_URL: 127.0.0.1:3100
        QRYN_LOGIN: a
        QRYN_PASSWORD: b
      run: node qryn.mjs >/dev/stdout & npm run test --forceExit
