# This workflow will validate qryn using nodejs + clickhouse

name: QRYN CI

on:
  push:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: docker run --name clickhouse -p 9000:9000 -p 8123:8123 -d clickhouse/clickhouse-server:23.8-alpine
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run postinstall
    - run: git submodule init
    - run: git submodule update
    - env:
        CLICKHOUSE_DB: loki
        CLICKHOUSE_TSDB: loki
        INTEGRATION_E2E: 1
        CLOKI_EXT_URL: 127.0.0.1:3100
      run: node qryn.js >/dev/stdout & npm run test --forceExit
